# Generated by Django 4.2.3 on 2023-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_title', models.CharField(max_length=100)),
                ('code_file', models.FileField(blank=True, null=True, upload_to='codes/')),
                ('code_price', models.CharField(blank=True, max_length=50, null=True)),
                ('code_final_price', models.CharField(blank=True, max_length=50, null=True)),
                ('code_detail', models.TextField(blank=True, null=True)),
                ('code_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_description', models.TextField()),
                ('video_price', models.CharField(blank=True, max_length=50, null=True)),
                ('video_price_final', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
